--EMMANUEL NIMO NYARK0
--SRI.41.008.043.21
--DATA SCIENCE BOOTCAMP


CREATE DATABASE PAYROLL_MANAGEMENT_SYSTEM
USE PAYROLL_MANAGEMENT_SYSTEM
--TABLE FOR THE EMPLOYEE PROFILE ENTITY--
CREATE TABLE EMPLOYEE(
EMPLOYEE_ID INT IDENTITY (10000,10) PRIMARY KEY,
FIRSTNAME VARCHAR(50),
LASTNAME VARCHAR(50),
GENDER VARCHAR(20),
CONTACT_NUMBER VARCHAR(50),
DEPARTMENT VARCHAR(50),
LOCATIONS VARCHAR(50)
)
--INSERTING DATA INTO THE VARIOUS FIELDS--
INSERT INTO EMPLOYEE(FIRSTNAME,LASTNAME,GENDER,CONTACT_NUMBER,DEPARTMENT,LOCATIONS)
VALUES('LOUIS','AFFUL','MALE','0557070123','ELECTRICAL','ELUBO')
INSERT INTO EMPLOYEE(FIRSTNAME,LASTNAME,GENDER,CONTACT_NUMBER,DEPARTMENT,LOCATIONS)
VALUES('PERRY','MICHAELS','MALE','0557070124','ELECTRICAL','EAST LEGON')
INSERT INTO EMPLOYEE(FIRSTNAME,LASTNAME,GENDER,CONTACT_NUMBER,DEPARTMENT,LOCATIONS)
VALUES('ANTHONY','STONES','MALE','0557070125','MARKETING','NIMA')
INSERT INTO EMPLOYEE(FIRSTNAME,LASTNAME,GENDER,CONTACT_NUMBER,DEPARTMENT,LOCATIONS)
VALUES('JOSHUA','FLYNN','MALE','0557070126','COMPUTING','SPINTEX')
INSERT INTO EMPLOYEE(FIRSTNAME,LASTNAME,GENDER,CONTACT_NUMBER,DEPARTMENT,LOCATIONS)
VALUES('EVELYN','OWENS','FEMALE','0557070127','MARKETING','EAST LEGON')
INSERT INTO EMPLOYEE(FIRSTNAME,LASTNAME,GENDER,CONTACT_NUMBER,DEPARTMENT,LOCATIONS)
VALUES('PRECIOUS','ANNAN','FEMALE','0557070128','ELECTRICAL','TANTRA HILLS')
INSERT INTO EMPLOYEE(FIRSTNAME,LASTNAME,GENDER,CONTACT_NUMBER,DEPARTMENT,LOCATIONS)
VALUES('NATHANIEL','OSEI','MALE','0557070129','COMPUTING','KOKROBITE')
INSERT INTO EMPLOYEE(FIRSTNAME,LASTNAME,GENDER,CONTACT_NUMBER,DEPARTMENT,LOCATIONS)
VALUES('PRISCILLA','OWUSU','FEMALE','0557070130','ELECTRICAL','MADINA')
INSERT INTO EMPLOYEE(FIRSTNAME,LASTNAME,GENDER,CONTACT_NUMBER,DEPARTMENT,LOCATIONS)
VALUES('NICK','PHILLIPS','MALE','0557070131','MARKETING','EAST LEGON')
INSERT INTO EMPLOYEE(FIRSTNAME,LASTNAME,GENDER,CONTACT_NUMBER,DEPARTMENT,LOCATIONS)
VALUES('ELLEN','OFORI','FEMALE','0557070132','ELECTRICAL','ACHIMOTA')
--CREATING TABLE FOR ALLOWANCE ENTITY--
CREATE TABLE ALLOWANCE(
ALLOWANCE_ID INT IDENTITY(20000 ,10) PRIMARY KEY,
RESPONSIBILITY_ALLOWANCE MONEY,
CAR_MAINTENANCE_ALLOWANCE MONEY,
FUEL_ALLOWANCE MONEY,
ELECTRICITY_ALLOWANCE MONEY,
SANITATION_ALLOWANCE MONEY,
MEDICAL_ALLOWANCE MONEY,
FK_EMPLOYEEID INT FOREIGN KEY REFERENCES EMPLOYEE(EMPLOYEE_ID)
)
--INSERTING VALUES INTO THE TABLE ALLOWANCE--
INSERT INTO ALLOWANCE(RESPONSIBILITY_ALLOWANCE,CAR_MAINTENANCE_ALLOWANCE,FUEL_ALLOWANCE,ELECTRICITY_ALLOWANCE,SANITATION_ALLOWANCE,MEDICAL_ALLOWANCE,FK_EMPLOYEEID)
VALUES ('100','50','100','20','20','50',10000)
INSERT INTO ALLOWANCE(RESPONSIBILITY_ALLOWANCE,CAR_MAINTENANCE_ALLOWANCE,FUEL_ALLOWANCE,ELECTRICITY_ALLOWANCE,SANITATION_ALLOWANCE,MEDICAL_ALLOWANCE,FK_EMPLOYEEID)
VALUES ('150','30','150','10','30','70',10010)
INSERT INTO ALLOWANCE(RESPONSIBILITY_ALLOWANCE,CAR_MAINTENANCE_ALLOWANCE,FUEL_ALLOWANCE,ELECTRICITY_ALLOWANCE,SANITATION_ALLOWANCE,MEDICAL_ALLOWANCE,FK_EMPLOYEEID)
VALUES ('130','40','140','15','10','100',10020)
INSERT INTO ALLOWANCE(RESPONSIBILITY_ALLOWANCE,CAR_MAINTENANCE_ALLOWANCE,FUEL_ALLOWANCE,ELECTRICITY_ALLOWANCE,SANITATION_ALLOWANCE,MEDICAL_ALLOWANCE,FK_EMPLOYEEID)
VALUES ('200','35','100','30','15','55',10030)
INSERT INTO ALLOWANCE(RESPONSIBILITY_ALLOWANCE,CAR_MAINTENANCE_ALLOWANCE,FUEL_ALLOWANCE,ELECTRICITY_ALLOWANCE,SANITATION_ALLOWANCE,MEDICAL_ALLOWANCE,FK_EMPLOYEEID)
VALUES ('180','55','130','25','50','50',10040)
INSERT INTO ALLOWANCE(RESPONSIBILITY_ALLOWANCE,CAR_MAINTENANCE_ALLOWANCE,FUEL_ALLOWANCE,ELECTRICITY_ALLOWANCE,SANITATION_ALLOWANCE,MEDICAL_ALLOWANCE,FK_EMPLOYEEID)
VALUES ('100','25','140','10','80','80',10050)
INSERT INTO ALLOWANCE(RESPONSIBILITY_ALLOWANCE,CAR_MAINTENANCE_ALLOWANCE,FUEL_ALLOWANCE,ELECTRICITY_ALLOWANCE,SANITATION_ALLOWANCE,MEDICAL_ALLOWANCE,FK_EMPLOYEEID)
VALUES ('150','45','190','15','30','90',10060)
INSERT INTO ALLOWANCE(RESPONSIBILITY_ALLOWANCE,CAR_MAINTENANCE_ALLOWANCE,FUEL_ALLOWANCE,ELECTRICITY_ALLOWANCE,SANITATION_ALLOWANCE,MEDICAL_ALLOWANCE,FK_EMPLOYEEID)
VALUES ('200','65','140','40','40','30',10070)
INSERT INTO ALLOWANCE(RESPONSIBILITY_ALLOWANCE,CAR_MAINTENANCE_ALLOWANCE,FUEL_ALLOWANCE,ELECTRICITY_ALLOWANCE,SANITATION_ALLOWANCE,MEDICAL_ALLOWANCE,FK_EMPLOYEEID)
VALUES ('210','10','155','35','35','75',10080)
INSERT INTO ALLOWANCE(RESPONSIBILITY_ALLOWANCE,CAR_MAINTENANCE_ALLOWANCE,FUEL_ALLOWANCE,ELECTRICITY_ALLOWANCE,SANITATION_ALLOWANCE,MEDICAL_ALLOWANCE,FK_EMPLOYEEID)
VALUES ('120','15','200','15','50','60',10090)
--CREATING TABLE FOR ARREARS AND CHARGES ENTITY--
CREATE TABLE ARREARS(
ARREARS_ID INT IDENTITY(30000 ,10) PRIMARY KEY,
SOCIAL_SECURITY MONEY,
WELFARE_FUND MONEY,
HOSTEL_BUS MONEY,
FK_EMPLOYEEID INT FOREIGN KEY REFERENCES EMPLOYEE(EMPLOYEE_ID)
)
--INSERTING VALUES INTO THE TABLE ARREARS--
INSERT INTO ARREARS( SOCIAL_SECURITY,WELFARE_FUND,HOSTEL_BUS,FK_EMPLOYEEID)
VALUES('40','20','10','10000')
INSERT INTO ARREARS( SOCIAL_SECURITY,WELFARE_FUND,HOSTEL_BUS,FK_EMPLOYEEID)
VALUES('40','20','00','10010')
INSERT INTO ARREARS( SOCIAL_SECURITY,WELFARE_FUND,HOSTEL_BUS,FK_EMPLOYEEID)
VALUES('40','20','20','10020')
INSERT INTO ARREARS( SOCIAL_SECURITY,WELFARE_FUND,HOSTEL_BUS,FK_EMPLOYEEID)
VALUES('40','20','10','10030')
INSERT INTO ARREARS( SOCIAL_SECURITY,WELFARE_FUND,HOSTEL_BUS,FK_EMPLOYEEID)
VALUES('40','20','00','10040')
INSERT INTO ARREARS( SOCIAL_SECURITY,WELFARE_FUND,HOSTEL_BUS,FK_EMPLOYEEID)
VALUES('40','20','00','10050')
INSERT INTO ARREARS( SOCIAL_SECURITY,WELFARE_FUND,HOSTEL_BUS,FK_EMPLOYEEID)
VALUES('40','20','20','10060')
INSERT INTO ARREARS( SOCIAL_SECURITY,WELFARE_FUND,HOSTEL_BUS,FK_EMPLOYEEID)
VALUES('40','20','10','10070')
INSERT INTO ARREARS( SOCIAL_SECURITY,WELFARE_FUND,HOSTEL_BUS,FK_EMPLOYEEID)
VALUES('40','20','10','10080')
INSERT INTO ARREARS( SOCIAL_SECURITY,WELFARE_FUND,HOSTEL_BUS,FK_EMPLOYEEID)
VALUES('40','20','00','10090')
--CREATING TABLE FOR SALARY ENTITY--
CREATE TABLE SALARY(
SALARY_ID INT IDENTITY(40000 ,10) PRIMARY KEY,
LAST_AMOUNT MONEY,
MONTHLY_SALARY MONEY,
ANNUAL_SALARY MONEY,
ACTIVE_DAYS INT,
FK_EMPLOYEEID INT FOREIGN KEY REFERENCES EMPLOYEE(EMPLOYEE_ID)
)
--INSERTING DATA INTO THE TABLE--
INSERT INTO SALARY(LAST_AMOUNT,MONTHLY_SALARY,ANNUAL_SALARY,ACTIVE_DAYS,FK_EMPLOYEEID)
VALUES('8000','7500','90000','25','10010')
INSERT INTO SALARY(LAST_AMOUNT,MONTHLY_SALARY,ANNUAL_SALARY,ACTIVE_DAYS,FK_EMPLOYEEID)
VALUES('7000','7000','84000','27','10010')
INSERT INTO SALARY(LAST_AMOUNT,MONTHLY_SALARY,ANNUAL_SALARY,ACTIVE_DAYS,FK_EMPLOYEEID)
VALUES('5000','4700','62000','22','10020')
INSERT INTO SALARY(LAST_AMOUNT,MONTHLY_SALARY,ANNUAL_SALARY,ACTIVE_DAYS,FK_EMPLOYEEID)
VALUES('8000','7500','90000','25','10030')
INSERT INTO SALARY(LAST_AMOUNT,MONTHLY_SALARY,ANNUAL_SALARY,ACTIVE_DAYS,FK_EMPLOYEEID)
VALUES('10000','10000','120000','30','10040')
INSERT INTO SALARY(LAST_AMOUNT,MONTHLY_SALARY,ANNUAL_SALARY,ACTIVE_DAYS,FK_EMPLOYEEID)
VALUES('9000','7500','92000','23','10050')
INSERT INTO SALARY(LAST_AMOUNT,MONTHLY_SALARY,ANNUAL_SALARY,ACTIVE_DAYS,FK_EMPLOYEEID)
VALUES('8000','7100','82000','24','10060')
INSERT INTO SALARY(LAST_AMOUNT,MONTHLY_SALARY,ANNUAL_SALARY,ACTIVE_DAYS,FK_EMPLOYEEID)
VALUES('8000','7500','90000','25','10070')
INSERT INTO SALARY(LAST_AMOUNT,MONTHLY_SALARY,ANNUAL_SALARY,ACTIVE_DAYS,FK_EMPLOYEEID)
VALUES('9200','9000','84000','29','10080')
INSERT INTO SALARY(LAST_AMOUNT,MONTHLY_SALARY,ANNUAL_SALARY,ACTIVE_DAYS,FK_EMPLOYEEID)
VALUES('5000','5300','72000','28','10090')
--CREATING TABLE FOR THE ENTITY LEAVE--
CREATE TABLE LEAVE(
LEAVE_ID INT IDENTITY(50000 ,10) PRIMARY KEY,
FROM_DATE DATE,
TO_DATE DATE,
REASON VARCHAR(50),
FK_EMPLOYEEID INT FOREIGN KEY REFERENCES EMPLOYEE(EMPLOYEE_ID)
)
--DISPLAYING THE TABLE--
SELECT * FROM LEAVE
--ENTERING THE DATA---
INSERT INTO LEAVE(FROM_DATE,TO_DATE,REASON,FK_EMPLOYEEID)
VALUES ('2010-6-10','2010-6-13','FUNERAL','10000')
INSERT INTO LEAVE(FROM_DATE,TO_DATE,REASON,FK_EMPLOYEEID)
VALUES ('2021-1-31','2021-2-3','WEDDING CEREMONY','10010')
INSERT INTO LEAVE(FROM_DATE,TO_DATE,REASON,FK_EMPLOYEEID)
VALUES ('2019-8-5','2019-8-20','MEDICATION','10020')
INSERT INTO LEAVE(FROM_DATE,TO_DATE,REASON,FK_EMPLOYEEID)
VALUES ('2020-9-10','2020-9-17','HOLIDAYS','10030')
INSERT INTO LEAVE(FROM_DATE,TO_DATE,REASON,FK_EMPLOYEEID)
VALUES ('2012-6-10','2012-7-10','TOUR AND TRAVEL','10040')
INSERT INTO LEAVE(FROM_DATE,TO_DATE,REASON,FK_EMPLOYEEID)
VALUES ('2017-6-1','2017-6-13','TRAVEL','10050')
INSERT INTO LEAVE(FROM_DATE,TO_DATE,REASON,FK_EMPLOYEEID)
VALUES ('2015-3-6','2015-3-15','THERAPY','10060')
INSERT INTO LEAVE(FROM_DATE,TO_DATE,REASON,FK_EMPLOYEEID)
VALUES ('2012-5-20','2012-5-30','OUTDOORING','10070')
INSERT INTO LEAVE(FROM_DATE,TO_DATE,REASON,FK_EMPLOYEEID)
VALUES ('2015-1-1','2015-2-1','BUSINESS TRIP','10080')
INSERT INTO LEAVE(FROM_DATE,TO_DATE,REASON,FK_EMPLOYEEID)
VALUES ('2016-6-10','2016-6-20','REST','10090')
--DISPLAY ALL THE TABLES--
SELECT*FROM EMPLOYEE
SELECT * FROM ALLOWANCE
SELECT *FROM ARREARS
SELECT * FROM SALARY
SELECT * FROM LEAVE